### ISSUE TITLE
Cannot install requirements.txt

### ISSUE THREAD

**Issue by Natglobe** [sindresorhus/weechat-notification-center#14]
I installed the newest version of the Map Master. I tried running it and got an error stating 
"No module named flask"
 I found out that it was an error due to not having "pip install -r requirements.txt" 
So whenever I input that I get this error message:
 [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/configargparse.py

I'm using a mac

**Comment by sindresorhus** [comment]
Wrong repo
