### ISSUE TITLE
Publish new release

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/weechat-notification-center#6]
I don't have time or interest in setting up WeeChat again, as I no longer use it. Happy to do a release if anyone confirms master is working or fixes it to work.

**Comment by sindresorhus** [comment]
// @thiagopnts @Silver-D @giannivh @limpep

**Comment by thiagopnts** [comment]
@sindresorhus Just tested master, its working fine. I can keep it.

**Comment by sindresorhus** [comment]
Thanks @thiagopnts. I've submitted an update :)
